version: '3'

services:
    nginx-proxy:
        image: jwilder/nginx-proxy
        restart: always
        ports:
        - "80:80"
        - "443:443"
        volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
        - certs:/etc/nginx/certs:ro
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        labels:
        - com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy

    letsencrypt:
        image: jrcs/letsencrypt-nginx-proxy-companion
        restart: always
        environment:
        - NGINX_PROXY_CONTAINER=nginx-proxy
        volumes:
        - certs:/etc/nginx/certs:rw
        - vhostd:/etc/nginx/vhost.d
        - html:/usr/share/nginx/html
        - /var/run/docker.sock:/var/run/docker.sock:ro
        - /root/projects/ema/ssl:/etc/nginx/certs:ro
    
    nodejs:
        build:
            context: .
            dockerfile: Dockerfile
        image: nodejs
        container_name: nodejs-build
        restart: unless-stopped
        volumes:
            - build:/app/dist/ema:rw

    www:
        image: nginx
        restart: always
        expose:
            - "80"
        volumes:
            - build:/usr/share/nginx/html:ro
            - ./nginx-custom.conf:/etc/nginx/conf.d/default.conf
        environment:
            - VIRTUAL_HOST=ematiendas.com.co,www.ematiendas.com.co
            - LETSENCRYPT_HOST=ematiendas.com.co,www.ematiendas.com.co
            - LETSENCRYPT_EMAIL=mail.ematiendas.com.co
volumes: 
    certs:
    html:
    vhostd:
    build:
